Sphinx-Society/kaizen-web-client

CODE_OF_CONDUCT.md
README.md

SSKW-10 Code of Conduct

---

CONTRIBUTING.md

SSKW-9 Contribution Guideline

---

.github/ISSUE_TEMPLATE/kaizen-bug-report---.md
.github/ISSUE_TEMPLATE/kaizen-feature-request---.md
.github/PULL_REQUEST_TEMPLATE.md

SSKW-2 Github Templates

---

.github/ISSUE_TEMPLATE/kaizen-feature-request---.md
.github/PULL_REQUEST_TEMPLATE.md

SSKW-16 Bug in github templates

---

.github/ISSUE_TEMPLATE/kaizen-bug-report---.md
.github/ISSUE_TEMPLATE/kaizen-feature-request---.md
.github/PULL_REQUEST_TEMPLATE.md

SSKW-22 Add checklist section a title in github templates

---

.eslintrc.json
cypress.json
cypress/integration/Surface.spec.js
cypress/support/commands.js
package-lock.json
package.json
src/client/components/atoms/Surface/story/Surface.story.mdx

SSKW-42 Modified Cypress tests to standardize recurring commands

---

cypress.json
package-lock.json
package.json
server.js
webpack.config.js

SSKW - 4 Heroku environment 

---

.github/workflows/deploy.yml

SSKW - 3 Github Actions

---

.github/workflows/deploy.yml

SSKW-3 Github Actions

---

src/client/components/atoms/Checkbox/Checkbox.jsx
src/client/components/atoms/Checkbox/Checkbox.scss
src/client/components/atoms/Checkbox/stories/Checkbox.stories.mdx
src/client/components/atoms/Checkbox/test/Checkbox.test.js
src/client/styles/general.scss

SSKW-53 Added Checkbox to use as atom check square

---

src/client/components/atoms/Checkbox/Checkbox.scss
src/client/components/atoms/Toogle/Toggle.jsx
src/client/components/atoms/Toogle/Toggle.scss
src/client/components/atoms/Toogle/stories/Toggle.stories.mdx
src/client/components/atoms/Toogle/test/Toggle.test.js

SSKW-26 Added component Toggle to use as atom

---

src/client/components/atoms/Surface/tests/Surface.test.js
src/client/components/atoms/TextInput/TextInput.jsx
src/client/components/atoms/TextInput/TextInput.scss
src/client/components/atoms/TextInput/stories/TextInput.stories.mdx
src/client/components/atoms/TextInput/tests/TextInput.test.js
src/client/components/molecules/DatepickerMenu/DatepickerMenu.jsx
src/client/components/molecules/DatepickerMenu/stories/DatepickerMenu.stories.mdx
src/client/components/molecules/DatepickerMenu/tests/DatepickerMenu.test.js
src/client/components/organisms/Datepicker/Datepicker.jsx
src/client/components/organisms/Datepicker/Datepicker.scss
src/client/components/organisms/Datepicker/stories/DatepickerWrapper.jsx
src/client/styles/mixins.scss

SSKW - 21 Text input atom

---

src/client/components/molecules/TopFilter/TopFilter.jsx
src/client/components/molecules/TopFilter/TopFilter.scss
src/client/components/molecules/TopFilter/stories/TopFilter.stories.mdx
src/client/components/molecules/TopFilter/tests/TopFilter.test.js

SSKW - 18 Top filter molecule

---

src/client/components/atoms/Select/Select.jsx
src/client/components/atoms/Select/Select.scss
src/client/components/atoms/Select/stories/Select.stories.mdx
src/client/components/atoms/Select/stories/SelectWrapper.jsx
src/client/components/atoms/Select/test/Select.test.js
src/client/styles/base.scss
src/client/styles/foundations/typography.scss

SSKW-24 Select atom

---

.github/workflows/ci.yml

SSKW-69 Modified GHaction to display test:coverage

---

src/client/components/atoms/Select/Select.scss
src/client/components/organisms/Navbar/Navbar.jsx
src/client/components/organisms/Navbar/Navbar.scss
src/client/components/organisms/Navbar/stories/Navbar.stories.mdx
src/client/components/organisms/Navbar/stories/Navbar.stories.scss
src/client/components/organisms/Navbar/test/Navbar.test.js
src/client/styles/general.scss

SSKW-33 Added files to structure 'Navbar'

---

README.md

SSKW-57 Update readme to show more about the project

---

src/client/components/atoms/ReadableField/ReadableField.jsx
src/client/components/atoms/ReadableField/ReadableField.scss
src/client/components/atoms/ReadableField/stories/ReadableField.stories.mdx
src/client/components/atoms/ReadableField/test/ReadableField.test.js

SSKW-76 Readable Field atom

---

src/client/components/atoms/ReadableField/ReadableField.jsx
src/client/components/atoms/ReadableField/ReadableField.scss
src/client/components/atoms/ReadableField/stories/ReadableField.stories.mdx
src/client/components/atoms/ReadableField/test/ReadableField.test.js
src/client/components/molecules/ListReadableFields/ListReadableFields.jsx
src/client/components/molecules/ListReadableFields/ListReadableFields.scss
src/client/components/molecules/ListReadableFields/stories/ListReadableFields.stories.mdx
src/client/components/molecules/ListReadableFields/test/ListReadableFields.test.js

SSKW-78 List Readable Fields molecule

---

.github/workflows/deploy.yml

SSKW-82 Storybook CI deployment fix

---

.github/workflows/deploy.yml

SSKW-82 Storybook CI deployment fix 

---

src/client/components/providers/MainViewProvider/MainViewProvider.jsx
src/client/components/providers/MainViewProvider/MainViewProvider.scss
src/client/components/providers/MainViewProvider/stories/MainViewProvider.stories.mdx
src/client/components/providers/MainViewProvider/tests/MainViewProvider.test.js

SSKW - 92 Main View Provider

---

src/client/components/atoms/Alert/Alert.jsx
src/client/components/atoms/Alert/Alert.scss
src/client/components/atoms/Button/Button.scss
src/client/components/pages/Login/Login.jsx
src/client/components/pages/TemplateEditor/TemplateEditor.jsx
src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
src/client/components/pages/UsersManagement/UsersManagement.jsx
src/client/components/providers/FeedbackProvider/FeedbackProvider.jsx
src/client/hooks/useOutsideClick/useOutsideClick.js
src/client/redux/templates/templates.actions.requests.js
src/client/styles/base.scss
src/client/styles/foundations/animations.scss
src/client/styles/foundations/colors.scss
src/client/styles/foundations/zIndexes.scss
src/client/styles/index.scss

SSKW - 97 Feedback Provider

---

src/client/components/organisms/Navbar/Navbar.jsx
src/client/components/pages/Settings/Settings.jsx
src/client/components/pages/Settings/Settings.scss
src/client/components/pages/Settings/test/Settings.test.js
src/client/routes/paths.js
src/client/routes/routes.js

SSKW-30 Settings Page

---

src/client/components/atoms/Button/Button.scss
src/client/components/organisms/Modal/Modal.jsx
src/client/components/organisms/Modal/Modal.scss
src/client/components/organisms/Modal/stories/Modal.stories.mdx
src/client/components/organisms/Modal/tests/Modal.test.js
src/client/components/pages/TemplateEditor/TemplateEditor.jsx
src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
src/client/components/pages/UsersManagement/UsersManagement.jsx
src/client/components/providers/ModalProvider/ModalProvider.jsx
src/client/components/providers/ModalProvider/ModalProvider.scss
src/client/redux/modalDialog/modalDialog.actions.js
src/client/redux/modalDialog/modalDialog.reducer.js
src/client/redux/reducer.js
src/client/styles/foundations/colors.scss

SSKW-99 Modal Provider and modal dialog

---

src/client/components/organisms/UserCard/UserCard.jsx
src/client/components/organisms/UserCard/stories/UserCard.stories.mdx
src/client/components/organisms/UserCard/tests/UserCard.test.js
src/client/components/pages/UsersManagement/UsersManagement.jsx

SSKW-106 Modified UserCard Storybook and more to fix a prop removed

---

src/client/components/atoms/Alert/Alert.jsx
src/client/components/atoms/Alert/Alert.scss
src/client/components/atoms/Alert/stories/Alert.stories.mdx
src/client/components/atoms/Alert/tests/Alert.test.js

SSKW-111 Add evidence and storybook to the Alert atom

---

src/client/services/Request.js
src/client/services/tests/Request.test.js

SSKW-124 Env variables not working on heroku

---

package-lock.json
package.json
src/client/services/Request.js
src/client/services/tests/Request.test.js
webpack.config.js
webpack.dev.config.js

SSKW-129 Change environment management way

---

src/client/components/organisms/Table/Table.jsx
src/client/components/organisms/UserCard/UserCard.scss
src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
src/client/components/pages/UsersManagement/UsersManagement.jsx
src/client/components/pages/UsersManagement/UsersManagement.scss
src/client/components/providers/MainViewProvider/MainViewProvider.jsx
src/client/components/providers/MainViewProvider/MainViewProvider.scss
src/client/redux/user/user.actions.requests.js
src/client/services/User.js
src/client/styles/general.scss

SSKW-119 When a template is searched and pagination is used, search is not consistent

---

src/client/components/organisms/TemplateCard/tests/TemplateCard.test.js
src/client/components/pages/Settings/test/Settings.test.js
src/client/utils/error.js

SSKW-143 Removed logs of unmet requirements in tests

---

src/client/components/pages/PatientTests/PatientTests.jsx
src/client/components/pages/ViewTest/ViewTest.jsx

SSKW-140  Integrate view tests page to doctor role

---

README.md

SSKW-137 Update Readme and other details

---

src/client/__mocks__/components/UserTableMock.js
src/client/components/atoms/DatepickerCarousel/DatepickerCarousel.jsx
src/client/components/atoms/DatepickerCarousel/tests/DatepickerCarousel.test.js
src/client/components/atoms/DatepickerDay/tests/DatepickerDay.test.js
src/client/components/organisms/Table/tests/Table.test.js

SSKW-144 Added test to cover table organism and other atoms
